[colors]
draw_bold_text_with_bright_colors = false

## miasma
indexed_colors = [{ index = 16, color = "0x222222"}]

[colors.bright]
black = "#666666"
red = "#685742"
green = "#5f875f"
yellow = "#b36d43"
blue = "#78824b"
magenta = "#bb7744"
cyan = "#c9a554"
white = "#d7c483"

[colors.normal]
black = "#222222"
red = "#685742"
green = "#5f875f"
yellow = "#b36d43"
blue = "#78824b"
magenta = "#bb7744"
cyan = "#c9a554"
white = "#d7c483"

[colors.primary]
background = "#222222"
foreground = "#c2c2b0"

[cursor]
style = "Underline"
vi_mode_style = "Block"

[font]
size = 10.0

[font.bold]
style = "Bold"

[font.normal]
family = " JetBrains Mono"
style = "Regular"

[window.dimensions]
columns = 128
lines = 24

[window.padding]
x = 20
y = 20
